### ISSUE TITLE
install conda_pkgs failed

### ISSUE THREAD

**Issue by fanchen26222** [singleron-RD/CeleScope#100]
hello,  I had failed to install other relevant software  listed in conda_pkgs.txt.  
mamba create -n CeleScope -y --file conda_pkgs.txt
 ![error](https://user-images.githubusercontent.com/64594004/155551714-61030487-c15d-4e27-9ddf-5bb5c33aa6a6.png)
Would you give me some advises how to fix this bug? Thank you very much.
Best wishes
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 927, in exception_converter
        raise e
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 921, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 879, in _wrapped_main
        result = do_call(args, p)
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 761, in do_call
        exit_code = create(args, parser)
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 664, in create
        return install(args, parser, "create")
      File "/bios-analysis10/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 613, in install
        downloaded = transaction.prompt(repos)
    RuntimeError: Found incorrect download: libffi. Aborting

`$ /bios-analysis10/miniconda3/bin/mamba create -n CeleScope -y --file conda_pkgs.txt`

**Comment by zhouyiqi91** [comment]
After some googling, I found a similar issue: https://github.com/mamba-org/mamba/issues/779

**Comment by zhouyiqi91** [comment]
@fanchen26222 Has the problem been resolved?

**Comment by fanchen26222** [comment]
> @fanchen26222 Has the problem been resolved?

NO! It's so sad!

**Comment by zhouyiqi91** [comment]
What if you install it directly using conda?
`conda create -n CeleScope -y --file conda_pkgs.txt`
