### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Leisanshi** [singleron-RD/CeleScope#120]
I was running mapping_tag, then celescope showed that:
$ celescope tag mapping_tag --barcode_fasta tag_barcode.fasta --linker_fasta tag_linker.fasta --thread 20 --fq DK8XFAXP_R2.fq.gz --outdir TAG --sample K2
2022-04-24 23:16:41,832 - celescope.tag.mapping_tag.mapping_tag - INFO - start...
2022-04-24 23:16:41,833 - celescope.tools.barcode.parse_pattern - INFO - start...
2022-04-24 23:16:41,834 - celescope.tools.barcode.parse_pattern - INFO - done. time used: 0:00:00.000155
2022-04-24 23:16:41,834 - celescope.tag.mapping_tag.run - INFO - start...
2022-04-24 23:16:41,834 - celescope.tools.step._clean_up - INFO - start...
2022-04-24 23:16:41,835 - celescope.tools.step._render_html - INFO - start...
2022-04-24 23:16:42,115 - celescope.tools.step._render_html - INFO - done. time used: 0:00:00.279737
2022-04-24 23:16:42,115 - celescope.tools.step._clean_up - INFO - done. time used: 0:00:00.280861
Traceback (most recent call last):
  File "/home/dell/.local/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/dell/.local/lib/python3.8/site-packages/celescope/celescope.py", line 43, in main
    args.func(args)
  File "/home/dell/.local/lib/python3.8/site-packages/celescope/tools/utils.py", line 44, in wrapper
    result = func(*args, **kwargs)
  File "/home/dell/.local/lib/python3.8/site-packages/celescope/tag/mapping_tag.py", line 82, in mapping_tag
    runner.run()
  File "/home/dell/.local/lib/python3.8/site-packages/celescope/tools/utils.py", line 44, in wrapper
    result = func(*args, **kwargs)
  File "/home/dell/.local/lib/python3.8/site-packages/celescope/tag/mapping_tag.py", line 240, in run
    self.process_read()
  File "/home/dell/.local/lib/python3.8/site-packages/celescope/tag/mapping_tag.py", line 148, in process_read
    umi = str(attr[1])
IndexError: list index out of range

How can I slove those problem?

**Comment by zhouyiqi91** [comment]
I think the problem is that DK8XFAXP_R2.fq.gz do not have UMI in it's read_name. 

`01.barcode/{sample}_2.fq(.gz)` Demultiplexed R2 reads. Barcode and UMI are contained in the read name. The format of the read name is `{barcode}_{UMI}_{read ID}`
```
@ACAGATTCGTACGCAACTGAGCCA_TCCGAAGCCCAT_1
NTTGTCAAGATGCTACCGTTCAGAGCACTGGTCATCGACACTGGGAACCTGAGGTGAGTTCGCGCGCAAG
+
#FFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF:F
@TGGAACAATGAAGAGAACTATGCA_TATCGAAGTAAT_2
NTTGTCAAGATGCTACCGTTCAGAGAGGGCTAGGCGTGTCATTTGGCGAGGTCCTGAGGTCATGGAGCC
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

In general, `multi_tag` should be used to run the tag pipeline:
https://github.com/singleron-RD/CeleScope/blob/master/docs/tag/multi_tag.md
