### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by BeyondMyPast228** [singleron-RD/CeleScope#14]
你好，新年快乐，我再运行CeleScope这个R包管道的Cutadapt步骤时，出现了以下报错，不知道是怎么回事？
Analysis complete for SC003BM1_2.fq.gz
2021-02-09 14:07:46,090 - celescope.tools.barcode.barcode - INFO - fastqc done!
2021-02-09 14:07:46,090 - celescope.tools.report - INFO - generate report: rna barcode
2021-02-09 14:07:46,121 - celescope.tools.report - INFO - generate report done!
2021-02-09 14:07:46,146 - celescope.tools.barcode.barcode - INFO - done. time used: 1:09:22.840118
2021-02-09 14:07:46,146 - celescope.tools.cutadapt.cutadapt - INFO - start...
2021-02-09 14:07:46,152 - celescope.tools.cutadapt.cutadapt - INFO - cutadapt -a polyT=A{18} -a p5=AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -n 2 -j 16 -m 20 --nextseq-trim=20 --overlap 10 -l 150 -o SC003BM1/02.cutadapt//SC003BM1_clean_2.fq.gz SC003BM1/01.barcode/SC003BM1_2.fq.gz
/data/singlecell/sc/COVID_19/BM1_3/SC003BM1_R1.fq.gz
/data/singlecell/sc/COVID_19/BM1_3/SC003BM1_R1.fq.gz
Traceback (most recent call last):
  File "/home/zfzf/.local/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/zfzf/.local/lib/python3.6/site-packages/celescope/celescope.py", line 566, in main
    args.func(args)
  File "/home/zfzf/.local/lib/python3.6/site-packages/celescope/rna/run.py", line 32, in run
    cutadapt(args)
  File "/home/zfzf/.local/lib/python3.6/site-packages/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/home/zfzf/.local/lib/python3.6/site-packages/celescope/tools/cutadapt.py", line 75, in cutadapt
    format_stat(args.outdir + '/cutadapt.log', args.sample)
  File "/home/zfzf/.local/lib/python3.6/site-packages/celescope/tools/cutadapt.py", line 30, in format_stat
    p_list.append({"item": attr[0], "value": attr[1]})
**IndexError: list index out of range**
我该如何解决这个错误呢？感谢您的帮助

**Comment by zhouyiqi91** [comment]
新年快乐！
这个问题可能是安装的cutadapt的版本!=1.1.7。
麻烦将02.cutadapt/cutadapt.log 的内容贴上

**Comment by BeyondMyPast228** [comment]
Hi@zhouyiqi91,
The error is:
This is cutadapt 1.17 with Python 3.6.9
Command line parameters: -a polyT=A{18} -a p5=AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -n 2 -j 16 -m 20 --nextseq-trim=20 --overlap 10 -l 150 -o SC003BM1/02.cutadapt//SC003BM1_clean_2.fq.gz SC003BM1/01.barcode/SC003BM1_2.fq.gz
Running on 16 cores
Trimming 2 adapters with at most 10.0% errors in single-end mode ...
ERROR: Traceback (most recent call last):
  File "/home/zfzf/.local/lib/python3.6/site-packages/cutadapt/pipeline.py", line 461, in run
    (n, bp1, bp2) = self._pipeline.process_reads()
  File "/home/zfzf/.local/lib/python3.6/site-packages/cutadapt/pipeline.py", line 220, in process_reads
    for read in self._reader:
  File "src/cutadapt/_seqio.pyx", line 181, in __iter__
  File "src/cutadapt/_seqio.pyx", line 82, in cutadapt._seqio.Sequence.__init__
**cutadapt.seqio.FormatError: In read named 'CACCTTACAACCGAGAACAAGCTA_TCGCAGTG_None_190542844': length of quality sequence (103) and length of read (150) do not match**

**cutadapt: error: In read named 'CACCTTACAACCGAGAACAAGCTA_TCGCAGTG_None_190542844': length of quality sequence (103) and length of read (150) do not match**

**Comment by zhouyiqi91** [comment]
报的错是fastq文件SC003BM1/01.barcode/SC003BM1_2.fq.gz中read名称为`CACCTTACAACCGAGAACAAGCTA_TCGCAGTG_None_190542844` 的read 质量值的长度（103）和 read长度（150) 不对应。
有可能是原始的R1 reads的fastq不完整导致的。
使用下面的命令检查一下原始的R1 reads fastq文件中第190542844个reads：
`less {R1 read fastq.gz} | sed -n 762171372,762171375p`

**Comment by zhouyiqi91** [comment]
> 报的错是fastq文件SC003BM1/01.barcode/SC003BM1_2.fq.gz中read名称为`CACCTTACAACCGAGAACAAGCTA_TCGCAGTG_None_190542844` 的read 质量值的长度（103）和 read长度（150) 不对应。
> 有可能是原始的R1 reads的fastq不完整导致的。
> 使用下面的命令检查一下原始的R1 reads fastq文件中第190542844个reads：
> `less {R1 read fastq.gz} | sed -n 762171372,762171375p`

如果这个样本包含多个fastq，上面这个命令可能不适用。
MD5 check一下原始的fastq文件。

**Comment by zhouyiqi91** [comment]
有另外的用户遇到了同样的问题，经检查是fastq文件不完整导致的。

**Comment by BeyondMyPast228** [comment]
谢谢您的帮助！


| |
井锐
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/3/2021 09:41，Tony ***@***.***> wrote：

有另外的用户遇到了同样的问题，经检查是fastq文件不完整导致的。
