### ISSUE TITLE
在05.count步骤出现问题，单独运行05.counts也会出现同样的问题

### ISSUE THREAD

**Issue by bogv127515** [singleron-RD/CeleScope#18]
我在使用Celescope做单细胞数据分析的时候在05.counts的步骤出现了问题
这是控制台的TraceBack
```
2021-04-11 22:20:48,959 - celescope.tools.utils.glob_genomeDir - INFO - done. time used: 0:00:00.000434
2021-04-11 22:20:48,959 - celescope.tools.count.bam2table - INFO - start...
[E::idx_find_and_load] Could not retrieve index file for './XXX/03.STAR/XXX_Aligned.sortedByCoord.out.bam'
2021-04-11 22:40:48,612 - celescope.tools.count.bam2table - INFO - done. time used: 0:19:59.653030
2021-04-11 22:40:48,677 - celescope.tools.count.matrix_10X - INFO - start...
Traceback (most recent call last):
  File "/root/anaconda3/bin/celescope", line 33, in <module>
    sys.exit(load_entry_point('celescope==1.1.7', 'console_scripts', 'celescope')())
  File "/root/anaconda3/lib/python3.7/site-packages/celescope-1.1.7-py3.7.egg/celescope/celescope.py", line 566, in main
    args.func(args)
  File "/root/anaconda3/lib/python3.7/site-packages/celescope-1.1.7-py3.7.egg/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/celescope-1.1.7-py3.7.egg/celescope/tools/count.py", line 389, in count
    matrix_10X(df, outdir, sample, gtf_file, dir_name=dir_name)
  File "/root/anaconda3/lib/python3.7/site-packages/celescope-1.1.7-py3.7.egg/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/celescope-1.1.7-py3.7.egg/celescope/tools/count.py", line 228, in matrix_10X
    mtx= coo_matrix((df_UMI.UMI, (df_UMI.index.labels[0], df_UMI.index.labels[1])))
AttributeError: 'MultiIndex' object has no attribute 'labels'
```
我没有太多的Python基础，不太明白这意味着什么，希望您能帮我看看问题要如何解决。

**Comment by zhouyiqi91** [comment]
这应该是pandas版本问题，尝试安装指定版本pandas。
`conda activate celescope; pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas==0.23.4`

**Comment by bogv127515** [comment]
**谢谢回复！**
但是在按照您的要求安装 pandas 0.23.4版本之后仍出现该问题

```
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> print(pd.__version__)
0.23.4
```

下面是conda celescope环境中的pip list
```
Package                       Version
----------------------------- -------------------
cachetools                    4.2.1
certifi                       2020.12.5
cffi                          1.14.5
chardet                       4.0.0
dataclasses                   0.8
google-api-core               1.26.3
google-auth                   1.28.1
google-auth-oauthlib          0.4.4
google-cloud-bigquery         2.13.1
google-cloud-bigquery-storage 2.4.0
google-cloud-core             1.6.0
google-crc32c                 1.1.2
google-resumable-media        1.2.0
googleapis-common-protos      1.53.0
grpcio                        1.37.0
idna                          2.10
libcst                        0.3.18
mutract                       1.1
mypy-extensions               0.4.3
numpy                         1.19.5
oauthlib                      3.1.0
packaging                     20.9
pandas                        0.23.4
pandas-gbq                    0.14.1
pip                           21.0.1
proto-plus                    1.18.1
protobuf                      3.15.8
pyarrow                       3.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
pydata-google-auth            1.1.0
pyparsing                     2.4.7
pysam                         0.16.0.1
python-dateutil               2.8.1
pytz                          2021.1
PyYAML                        5.4.1
requests                      2.25.1
requests-oauthlib             1.3.0
rsa                           4.7.2
scipy                         1.5.4
setuptools                    52.0.0.post20210125
six                           1.15.0
typing-extensions             3.7.4.3
typing-inspect                0.6.0
urllib3                       1.26.4
wheel                         0.36.2
```
*我不确定以上python包的版本是否被更改过，是否可能是其它包的版本出了问题？*

**Comment by zhouyiqi91** [comment]
1. 我注意到pip list显示的环境中少了一些包：例如没有celescope, cutadapt, xopen, 可以查看一下这些包安装在了哪里，例如：
` python -c "import celescope;print(celescope.__file__)"`

2. `'MultiIndex' object has no attribute 'labels'` 这个报错是因为celescope调用了高于0.23.4版本的pandas导致的:
>Changed in version 0.24.0: MultiIndex.labels has been renamed to MultiIndex.codes and MultiIndex.set_labels to MultiIndex.set_codes.
 
很有可能你使用的celescope并不在conda celescope环境中，调用的不是celescope环境中的pandas

**Comment by bogv127515** [comment]
**谢谢，我终于找到了问题！**
通过 ```which celescope``` 来查看程序位置的时候我发现它并不指向~/anaconda3/envs/celescope/bin/celescope，而是指向了~/anaconda3/bin/celescope。导致错误调用了base环境中的pandas=3.1.0
