### ISSUE TITLE
vdj mkref no longer available?

### ISSUE THREAD

**Issue by m-fayer** [singleron-RD/CeleScope#204]
Hi, following the commands in [this page](https://github.com/singleron-RD/CeleScope/blob/master/docs/vdj/multi_vdj.md), when I type command "celescope vdj mkref", an error occurred:

`celescope vdj: error: invalid choice: 'mkref' (choose from 'sample', 'barcode', 'cutadapt', 'consensus', 'mapping_vdj', 'count_vdj')`

It looks mkref is no longer available in "celescope vdj"? If so, how should I index vdj reference? Thanks.

**Comment by zhouyiqi91** [comment]
`celescope vdj mkref` is only available in the lastest beta version v1.14.0b0. Sorry for the confusion.
```
pip install celescope==1.14.0b0
```

**Comment by m-fayer** [comment]
Thanks. I installed 1.14.0b0 by commands below:

```
mamba create -y --prefix /install/path --file CeleScope/conda_pkgs.txt
conda activate /install/path
pip install celescope==1.14.0b0
```

The installation looks ok. Then I used commands "celescope vdj mkref human TR" to index reference. The screen output is:

<pre>
2022-12-08 17:31:36,150 - celescope.vdj.mkref.combine_seq - INFO - start...
2022-12-08 17:31:36,282 - celescope.vdj.mkref.combine_seq - INFO - done. time used: 0:00:00.130503
2022-12-08 17:31:36,283 - celescope.vdj.mkref.build_index - INFO - start...
<b>/bin/sh: edit_imgt_file.pl: command not found</b>
Traceback (most recent call last):
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/celescope.py", line 44, in main
    args.func(args)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 75, in mkref
    runner()
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 36, in __call__
    self.build_index()
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/tools/utils.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 69, in build_index
    subprocess.check_call(f"edit_imgt_file.pl {file} > {out_file_name}.fa", shell=True)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'edit_imgt_file.pl TRV.fasta > TRV.fa' returned non-zero exit status 127.
</pre>

Then I ran "celescope vdj mkref human IG", the output is similar:

<pre>
2022-12-08 17:31:39,733 - celescope.vdj.mkref.combine_seq - INFO - start...
2022-12-08 17:31:39,848 - celescope.vdj.mkref.combine_seq - INFO - done. time used: 0:00:00.113806
2022-12-08 17:31:39,848 - celescope.vdj.mkref.build_index - INFO - start...
<b>/bin/sh: edit_imgt_file.pl: command not found</b>
Traceback (most recent call last):
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/celescope.py", line 44, in main
    args.func(args)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 75, in mkref
    runner()
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 36, in __call__
    self.build_index()
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/tools/utils.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 69, in build_index
    subprocess.check_call(f"edit_imgt_file.pl {file} > {out_file_name}.fa", shell=True)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'edit_imgt_file.pl IGD.fasta > IGD.fa' returned non-zero exit status 127.
</pre>

Anything wrong?

**Comment by zhouyiqi91** [comment]
`edit_imgt_file.pl` is icluded with igblast.
https://github.com/singleron-RD/CeleScope/blob/01df672ce67088f0a812207d4daabc2f4ef2eb83/conda_pkgs.txt#L10

You can check if you have installed igblast with:
```
which igblastn
which edit_imgt_file.pl
```

**Comment by m-fayer** [comment]
Thanks. Problem solved!
