### ISSUE TITLE
barcode tool usage

### ISSUE THREAD

**Issue by singlecoated** [singleron-RD/CeleScope#231]
Dear developer(s),

I'm facing an issue while trying to run the barcode tool in order to extract cell barcodes and UMIs from reads as part of some ongoing tests.

Essentially, the apparent usage of the tool (see output below) seems to be different from what is indicated in the tool man page (https://github.com/singleron-RD/CeleScope/blob/master/docs/tools/barcode.md), where it seems to expect parameters indicating location of fastq files etc.

But this is what the tool says with -h

usage: barcode.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                  [-k TESTNAMEPATTERNS]
                  [tests [tests ...]]

positional arguments:
  tests                a list of any number of test modules, classes and test
                       methods.

optional arguments:
  -h, --help           show this help message and exit
  -v, --verbose        Verbose output
  -q, --quiet          Quiet output
  --locals             Show local variables in tracebacks
  -f, --failfast       Stop on first fail or error
  -c, --catch          Catch Ctrl-C and display results so far
  -b, --buffer         Buffer stdout and stderr during tests
  -k TESTNAMEPATTERNS  Only run tests which match the given substring

Examples:
  barcode.py                           - run default set of tests
  barcode.py MyTestSuite               - run suite 'MyTestSuite'
  barcode.py MyTestCase.testSomething  - run MyTestCase.testSomething
  barcode.py MyTestCase                - run all 'test*' test methods
                                       in MyTestCase 

It's my very first time running CeleScope tools, so my apologies if I'm missing something obvious.

Thanks in advance for your help.

**Comment by zhouyiqi91** [comment]
You probably ran the `barcode.py` program directly from source. For example:
`python celescope/tools/barcode.py -h`
This is not the correct way to run the program.
After you have installed celescope, you can run the barcode program like this:
`celescope rna barcode -h`

Please take a look at
https://github.com/singleron-RD/CeleScope/blob/master/docs/quick_start.md

**Comment by singlecoated** [comment]
That was exactly the case, I will try running the program within celescope itself. Many thanks for your fast help !

**Comment by singlecoated** [comment]
Good morning,

thanks to your previous help I could successfully run the barcode tool calling it from the celescope binary, much appreciated.

Unfortunately, I now have a new error message. Here I paste the output with the calling command and messages. I can identify a previous warning related to the sample_summary.metrics and an 'assay not found', I'm not sure if it has something to do with that.

Just to clarify, I am running the barcode tool on a pair of fq files independently, don't have any full run of celescope (in case some kind of initial sampleinfo or config files have to be provided as is the case in other pipelines).

Also, barcode whitelist file and linkers are the ones dowloaded from this same github for the v3.0 chemistry.

Many thanks in advance.

--- CELESCOPE OUTPUT START ---

2023-04-12 12:03:50,137 - celescope.tools.barcode.barcode - INFO - start...
Args: Namespace(subparser_assay='rna', chemistry='auto', pattern=None, whitelist='./singleron_v3_bclist.txt', linker='./singleron_v3_linkers.txt', lowQual=0, lowNum=2, nopolyT=False, noLinker=False, filterNoPolyT=False, allowNoLinker=False, gzip=True, output_R1=False, fq1='../../../data/rawDATA_TargetedAmplification/TA-1C_AHW75CBGXL_R1_PE150.fastq.gz', fq2='../../../data/rawDATA_TargetedAmplification/TA-1C_AHW75CBGXL_R2_PE150.fastq.gz', match_dir=None, outdir='./', sample='test', thread='12', debug=True, func=<function barcode at 0x7f26b6653550>)
2023-04-12 12:03:50,137 - celescope.tools.barcode.parse_pattern - INFO - start...
2023-04-12 12:03:50,137 - celescope.tools.barcode.parse_pattern - INFO - done. time used: 0:00:00.000118
2023-04-12 12:03:50,157 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,162 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.005109
2023-04-12 12:03:50,167 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,177 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.010517
2023-04-12 12:03:50,177 - celescope.tools.barcode.parse_pattern - INFO - start...
2023-04-12 12:03:50,177 - celescope.tools.barcode.parse_pattern - INFO - done. time used: 0:00:00.000016
2023-04-12 12:03:50,192 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,196 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.004317
2023-04-12 12:03:50,197 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,284 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.086985
2023-04-12 12:03:50,285 - celescope.tools.barcode.parse_pattern - INFO - start...
2023-04-12 12:03:50,285 - celescope.tools.barcode.parse_pattern - INFO - done. time used: 0:00:00.000041
2023-04-12 12:03:50,287 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,332 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.045505
2023-04-12 12:03:50,334 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,461 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.127026
2023-04-12 12:03:50,461 - celescope.tools.barcode.parse_pattern - INFO - start...
2023-04-12 12:03:50,461 - celescope.tools.barcode.parse_pattern - INFO - done. time used: 0:00:00.000044
2023-04-12 12:03:50,463 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,465 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.001743
2023-04-12 12:03:50,497 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,590 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.093359
2023-04-12 12:03:50,591 - celescope.tools.barcode.parse_pattern - INFO - start...
2023-04-12 12:03:50,591 - celescope.tools.barcode.parse_pattern - INFO - done. time used: 0:00:00.000046
2023-04-12 12:03:50,624 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,625 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.001766
2023-04-12 12:03:50,626 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-04-12 12:03:50,802 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.175075
2023-04-12 12:03:50,802 - celescope.tools.barcode.check_chemistry - INFO - start...
../../../data/rawDATA_TargetedAmplification/TA-1C_AHW75CBGXL_R1_PE150.fastq.gz
2023-04-12 12:03:50,802 - celescope.tools.barcode.get_chemistry - INFO - start...
2023-04-12 12:03:51,052 - celescope.tools.barcode.get_chemistry - INFO - [('scopeV3.0.1', 9490), ('scopeV2.2.1', 1), ('scopeV2.1.1', 0)]
2023-04-12 12:03:51,053 - celescope.tools.barcode.get_chemistry - INFO - chemistry: scopeV3.0.1
2023-04-12 12:03:51,053 - celescope.tools.barcode.get_chemistry - INFO - done. time used: 0:00:00.250556
2023-04-12 12:03:51,053 - celescope.tools.barcode.check_chemistry - INFO - done. time used: 0:00:00.250662
2023-04-12 12:03:51,053 - celescope.tools.step.get_slot_key - INFO - start...
2023-04-12 12:03:51,053 - celescope.tools.step.get_slot_key - WARNING - Assay not found in sample_summary.metrics
Traceback (most recent call last):
  File "/home/oreina/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/oreina/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/celescope.py", line 45, in main
    args.func(args)
  File "/home/oreina/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/home/oreina/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/barcode.py", line 728, in barcode
    with Barcode(args, display_title='Demultiplexing') as runner:
  File "/home/oreina/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/barcode.py", line 200, in __init__
    self._assay = self.get_slot_key(
  File "/home/oreina/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/home/oreina/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/step.py", line 205, in get_slot_key
    return self.__content_dict[slot][step_name + '_summary'][key]
KeyError: 'sample_summary'

--- CELESCOPE OUTPUT END ---

**Comment by zhouyiqi91** [comment]
Sorry for the late reply. Running the `barcode` step requires running the `sample` step first.
```
celescope rna sample \
 --outdir ./ \
 --sample test \
 --chemistry auto \
 --fq1 ../../../data/rawDATA_TargetedAmplification/TA-1C_AHW75CBGXL_R1_PE150.fastq.gz
```

**Comment by singlecoated** [comment]
No worries, and MANY thanks for your help, I could run everything without problems now.

Warm regards.
