### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Zluei** [singleron-RD/CeleScope#232]
Dear all,
I get an error when I run the following command.I haven't found the problem for a long time, I hope you can help me！
ERROR:
Traceback (most recent call last):
  File "/home/zhangleilei/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/celescope.py", line 44, in main
    args.func(args)
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/sample.py", line 64, in sample
    with Sample(args) as runner:
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/sample.py", line 26, in __init__
    Step.__init__(self, args)
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/step.py", line 78, in __init__
    self.__content_dict[slot] = json.load(f)
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/zhangleilei/miniconda3/envs/celescope/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

COMMAND: celescope rna sample --outdir PND1/00.sample --sample PND1 --thread 16 --chemistry auto  --fq1 /mnt/My_disk/Zhang_leilei/scRNA_PND/PND1/Rawdata/PND1_1.fastq.gz

**Comment by zhouyiqi91** [comment]
Two hidden files .metrics.json and .data.json will be generated under outdir. This error may be caused by an invalid json file generated by a previous unsuccessful run.
Deleting outdir (in this case the `PND1` directory), and re-running should resolve the error.

**Comment by Zluei** [comment]
Wow! Thanks! I solved this problem by adopting your method. Thank you so much !!!
