### ISSUE TITLE
celescope vdj mapping_vdj  CalledProcessError error

### ISSUE THREAD

**Issue by liujiayu1997** [singleron-RD/CeleScope#248]
**Describe the bug**
When I run the command :
celescope vdj mapping_vdj --outdir ./Zhoujianxin_GC/04.mapping_vdj --sample Zhoujianxin_GC --thread 8 --ref_path "/mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR" --type TCR --species human  --fasta ./mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/Zhoujianxin_GC/03.consensus/Zhoujianxin_GC_consensus.fasta

I get the error like this:
Args: Namespace(subparser_assay='vdj', ref_path='/mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR', type='TCR', species='human', split_fasta=False, fasta='./mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/Zhoujianxin_GC/03.consensus/Zhoujianxin_GC_consensus.fasta', outdir='./Zhoujianxin_GC/04.mapping_vdj', sample='Zhoujianxin_GC', thread='1', debug=False, func=<function mapping_vdj at 0x7f0521fdfe20>)
2023-07-09 13:39:50,596 - celescope.vdj.mapping_vdj.igblast - INFO - start...
2023-07-09 13:39:50,596 - celescope.vdj.mapping_vdj.igblast - INFO - igblastn -query ./mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/Zhoujianxin_GC/03.consensus/Zhoujianxin_GC_consensus.fasta -organism human -ig_seqtype TCR -auxiliary_data optional_file/human_gl.aux -num_threads 1 -germline_db_V /mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR/TRV.fa -germline_db_D /mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR/TRD.fa -germline_db_J /mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR/TRJ.fa -domain_system imgt -show_translation -outfmt 19 -out ./Zhoujianxin_GC/04.mapping_vdj/Zhoujianxin_GC_airr.tsv 
BLAST query/options error: Germline annotation database human/human_TR_V could not be found in [internal_data] directory
Please refer to the BLAST+ user manual.
2023-07-09 13:39:51,891 - celescope.tools.step._clean_up - INFO - start...
2023-07-09 13:39:51,893 - celescope.tools.step._render_html - INFO - start...
2023-07-09 13:39:52,295 - celescope.tools.step._render_html - INFO - done. time used: 0:00:00.402076
2023-07-09 13:39:52,295 - celescope.tools.step._clean_up - INFO - done. time used: 0:00:00.404104
Traceback (most recent call last):
  File "/home/xiaying/anaconda3/envs/Celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xiaying/anaconda3/envs/Celescope/lib/python3.11/site-packages/celescope/celescope.py", line 43, in main
    args.func(args)
  File "/home/xiaying/anaconda3/envs/Celescope/lib/python3.11/site-packages/celescope/vdj/mapping_vdj.py", line 220, in mapping_vdj
    runner.run()
  File "/home/xiaying/anaconda3/envs/Celescope/lib/python3.11/site-packages/celescope/vdj/mapping_vdj.py", line 56, in run
    self.igblast(fasta=self.args.fasta, airr_out=self.airr_out[0])
  File "/home/xiaying/anaconda3/envs/Celescope/lib/python3.11/site-packages/celescope/tools/utils.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiaying/anaconda3/envs/Celescope/lib/python3.11/site-packages/celescope/vdj/mapping_vdj.py", line 105, in igblast
    subprocess.check_call(cmd, shell=True)
  File "/home/xiaying/anaconda3/envs/Celescope/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'igblastn -query ./mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/Zhoujianxin_GC/03.consensus/Zhoujianxin_GC_consensus.fasta -organism human -ig_seqtype TCR -auxiliary_data optional_file/human_gl.aux -num_threads 1 -germline_db_V /mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR/TRV.fa -germline_db_D /mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR/TRD.fa -germline_db_J /mnt/b95b4929-e82a-40e3-aa94-c772e90d8aeb/cellranger/xingeyuan/TCR/vdj/TR/TRJ.fa -domain_system imgt -show_translation -outfmt 19 -out ./Zhoujianxin_GC/04.mapping_vdj/Zhoujianxin_GC_airr.tsv ' returned non-zero exit status 1.

I don't know how to solve it, my igblastn version is 1.18.0 or 1.21.0, but neither of this version work.

**Comment by Chenjunjie1996** [comment]
Did you build reference successfully before running?
https://github.com/singleron-RD/CeleScope/blob/master/doc/assay/multi_vdj.md
