### ISSUE TITLE
about a strange error

### ISSUE THREAD

**Issue by evenDDDDD** [singleron-RD/CeleScope#250]
hi, When I run the following code, 
`celescope rna sample --outdir ./B2T/00.sample --sample B2T --thread 4 --chemistry scopeV1  --fq1 ./SRR15927887_1.fastq.gz,./SRR15927888_1.fastq.gz 
celescope rna prep_map --outdir ./B2T/01.prep_map --sample B2T --thread 4 --chemistry scopeV1 --lowNum 2 --minimum_length 20 --nextseq_trim 20 --overlap 10 --genomeDir ./human_fasta --outFilterMatchNmin 50 --outFilterMultimapNmax 1 --starMem 30  --fq1 ./SRR15927887_1.fastq.gz,./SRR15927888_1.fastq.gz --fq2 ./SRR15927887_2.fastq.gz,./SRR15927888_2.fastq.gz 
`
I get this error
```
`2023-07-20 16:01:40,866 - celescope.tools.prep_map.prep_map - INFO - start...
Args: Namespace(STAR_param='', allowNoLinker=False, chemistry='scopeV1', cutadapt_param='', debug=False, filterNoPolyT=False, fq1='/mnt/b14Tb/lldeng/PRJNA764023/SRR15927887_1.fastq.gz,/mnt/b14Tb/lldeng/PRJNA764023/SRR15927888_1.fastq.gz', fq2='/mnt/b14Tb/lldeng/PRJNA764023/SRR15927887_2.fastq.gz,/mnt/b14Tb/lldeng/PRJNA764023/SRR15927888_2.fastq.gz', func=<function prep_map at 0x7f87be1ffaf0>, genomeDir='/mnt/b14Tb/lldeng/PRJNA764023/human_fasta', gzip=False, linker=None, lowNum=2, lowQual=0, match_dir=None, minimum_length='20', nextseq_trim='20', noLinker=False, nopolyT=False, outFilterMatchNmin='50', outFilterMultimapNmax='1', out_unmapped=False, outdir='/mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map', output_R1=False, overlap='10', pattern=None, sample='B2T', starMem='30', stdout=False, subparser_assay='rna', thread='4', whitelist=None)
2023-07-20 16:01:40,867 - celescope.tools.prep_map.run - INFO - start...
2023-07-20 16:01:40,868 - celescope.tools.star_mixin.get_star_cmd - INFO - start...
2023-07-20 16:01:40,868 - celescope.tools.star_mixin.get_star_cmd - INFO - STAR --runThreadN 4 --genomeDir /mnt/b14Tb/lldeng/PRJNA764023/human_fasta --outSAMmultNmax 1 --outFilterMultimapNmax 1 --outSAMtype BAM Unsorted --outFilterMatchNmin 50  --readFilesIn /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO --outFileNamePrefix /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_
2023-07-20 16:01:40,868 - celescope.tools.star_mixin.get_star_cmd - INFO - done. time used: 0:00:00.000045
mkfifo /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_bc2.FIFO /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO
celescope rna barcode --chemistry scopeV1 --lowNum 2 --fq1 /mnt/b14Tb/lldeng/PRJNA764023/SRR15927887_1.fastq.gz,/mnt/b14Tb/lldeng/PRJNA764023/SRR15927888_1.fastq.gz --fq2 /mnt/b14Tb/lldeng/PRJNA764023/SRR15927887_2.fastq.gz,/mnt/b14Tb/lldeng/PRJNA764023/SRR15927888_2.fastq.gz --outdir /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map --sample B2T --thread 4 --stdout >> /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_bc2.FIFO &
cutadapt -a polyA=A{18}  -j 4 -m 20 --nextseq-trim=20 --overlap 10  --json /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_cutadapt.json -o /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_bc2.FIFO  &
STAR --runThreadN 4 --genomeDir /mnt/b14Tb/lldeng/PRJNA764023/human_fasta --outSAMmultNmax 1 --outFilterMultimapNmax 1 --outSAMtype BAM Unsorted --outFilterMatchNmin 50  --readFilesIn /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO --outFileNamePrefix /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_
rm /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_bc2.FIFO
/mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO

mkfifo: cannot create fifo '/mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO': File exists
/bin/sh: 4: STAR: not found
2023-07-20 16:01:40,886 - celescope.tools.prep_map.run - INFO - done. time used: 0:00:00.019130
Args: Namespace(STAR_param='', allowNoLinker=False, chemistry='scopeV1', cutadapt_param='', debug=False, filterNoPolyT=False, fq1='/mnt/b14Tb/lldeng/PRJNA764023/SRR15927887_1.fastq.gz,/mnt/b14Tb/lldeng/PRJNA764023/SRR15927888_1.fastq.gz', fq2='/mnt/b14Tb/lldeng/PRJNA764023/SRR15927887_2.fastq.gz,/mnt/b14Tb/lldeng/PRJNA764023/SRR15927888_2.fastq.gz', func=<function prep_map at 0x7f87be1ffaf0>, genomeDir='/mnt/b14Tb/lldeng/PRJNA764023/human_fasta', gzip=False, linker=None, lowNum=2, lowQual=0, match_dir=None, minimum_length='20', nextseq_trim='20', noLinker=False, nopolyT=False, outFilterMatchNmin='50', outFilterMultimapNmax='1', out_unmapped=False, outdir='/mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map', output_R1=False, overlap='10', pattern=None, sample='B2T', starMem='30', stdout=False, subparser_assay='rna', thread='4', whitelist=None)
2023-07-20 16:01:40,887 - celescope.tools.step._clean_up - INFO - start...
2023-07-20 16:01:40,888 - celescope.tools.step._render_html - INFO - start...
This is cutadapt 3.7 with Python 3.8.12
Command line parameters: -a polyA=A{18} -j 4 -m 20 --nextseq-trim=20 --overlap 10 --json /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_cutadapt.json -o /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_ct2.FIFO /mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_bc2.FIFO
Processing reads on 4 cores in single-end mode ...
ERROR: Traceback (most recent call last):
  File "/home/lldeng/.conda/envs/r4.1/lib/python3.8/site-packages/cutadapt/pipeline.py", line 669, in run
    with self._opener.xopen(self.path, "rb") as f:
  File "/home/lldeng/.conda/envs/r4.1/lib/python3.8/site-packages/cutadapt/utils.py", line 204, in xopen
    f = open_raise_limit(
  File "/home/lldeng/.conda/envs/r4.1/lib/python3.8/site-packages/cutadapt/utils.py", line 51, in open_raise_limit
    f = func(*args, **kwargs)
  File "/home/lldeng/.conda/envs/r4.1/lib/python3.8/site-packages/xopen/__init__.py", line 1291, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/b14Tb/lldeng/PRJNA764023/B2T/01.prep_map/B2T_bc2.FIFO'`

```
It seems that the` ./B2T/01.prep_map/B2T_bc2.FIFO` file was deleted. I wonder what happened.
My celescope version is 1.16.2, which is installed directly via `pip install celescope`.

Sincerely hope to get your help!!!!

**Comment by zhouyiqi91** [comment]
`/bin/sh: 4: STAR: not found`

Maybe you didn't activate the conda environment?

**Comment by evenDDDDD** [comment]
Hi，I made sure that the environment was activated. And in order to prevent being affected by the previously established environment, I created a new environment and only installed celescope and related packages.
```
Package         Version
--------------- -------
anndata         0.7.6
biopython       1.81
blosc2          2.0.0
celescope       1.16.2
cutadapt        3.7
cycler          0.11.0
Cython          3.0.0
dnaio           0.10.0
fonttools       4.41.0
h5py            3.9.0
igraph          0.10.6
iniconfig       2.0.0
isal            1.1.0
Jinja2          3.1.2
joblib          1.3.1
kaleido         0.2.1
kiwisolver      1.4.4
leidenalg       0.10.1
llvmlite        0.40.1
MarkupSafe      2.1.3
matplotlib      3.5.3
mizani          0.9.2
msgpack         1.0.5
natsort         8.4.0
networkx        3.1
numba           0.57.1
numexpr         2.8.4
numpy           1.24.4
packaging       23.1
pandas          1.4.2
patsy           0.5.3
Pillow          10.0.0
pip             23.2
plotly          5.15.0
plotnine        0.9.0
pluggy          1.2.0
py-cpuinfo      9.0.0
pynndescent     0.5.10
pyparsing       3.1.0
pysam           0.21.0
pytest          7.4.0
python-dateutil 2.8.2
pytz            2023.3
scanpy          1.8.2
scikit-learn    1.2.2
scipy           1.11.1
seaborn         0.12.2
setuptools      68.0.0
sinfo           0.3.4
six             1.16.0
statsmodels     0.14.0
stdlib-list     0.9.0
tables          3.8.0
tenacity        8.2.2
texttable       1.6.7
threadpoolctl   3.2.0
tqdm            4.65.0
umap-learn      0.5.3
wheel           0.40.0
xlrd            1.2.0
xopen           1.7.0
```
What I don't understand is that it seems that `B2T_ct2.FIFO` and `B2T_bc2.FIFO` in celoscope `rna prep_map --outdir ./PRJNA764023/B2T/01.prep_map --sample B2T --thread 4 --chemistry scopeV1 --lowNum 2 --minimum_length 20 --nextse q_trim 20 --overlap 10 --genomeDir ./human_fasta --outFilterMatchNmin 50 --outFilterMultimapNmax 1 --starMem 30 --fq1 ./SRR15927887_1.f astq.gz, ./SRR15927888_1.fastq.gz --fq2 ./SRR15927887_2.fastq.gz, ./SRR 15927888_2.fastq.gz` is processed at the same time, why `B2T_ct2.FIFO` exists, but `B2T_bc2.FIFO` does not.

Still looking forward to your reply!!!

**Comment by zhouyiqi91** [comment]
The problem is that STAR(https://github.com/singleron-RD/CeleScope/blob/master/conda_pkgs.txt#L2) is not found.
STAR is not a python package. It is installed via conda, not pip.
You can check whether STAR has been installed:
```
conda activate {env_name}
which STAR
```

Have you run the second step of installation?
https://github.com/singleron-RD/CeleScope/blob/master/doc/user_guide.md
> Create conda environment and install conda packages. It is recommended to use [mamba](https://github.com/mamba-org/mamba) (which is a faster replacement for Conda):
conda install mamba
cd CeleScope
mamba create -n celescope -y --file conda_pkgs.txt
