### ISSUE TITLE
Some ISSUEs concerning about constructing REFERENCE on vdj sequencing and full length immune receptor sequencing

### ISSUE THREAD

**Issue by Gethell** [singleron-RD/CeleScope#269]
**Description**
When I did as the tutorial on official [tweets](https://mp.weixin.qq.com/s/hqh7DJPzLsC45LepTI8Q7Q), I met some issues as running the following codes: 
`celescope vdj mkref human TR`
but encounted issue like :
>  Traceback (most recent call last):
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 81, in mkref
    runner()
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 35, in __call__
    self.combine_seq()
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 59, in combine_seq
    assert len(imgt_files) == 7
AssertionError

And I run the code: 
`celescope vdj mkref human IG`
I met another issue like:
 > `Building a new DB, current time: 11/01/2023 15:27:28
New DB name:   /bios-store1/home/logcoin/Reference/hs_vdj/Homo_sapiens/IG/human_cele_BR/IGV.fa
New DB title:  IGV.fa
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /bios-store1/home/logcoin/Reference/hs_vdj/Homo_sapiens/IG/human_cele_BR/IGV.fa
Keep MBits: T
Maximum file size: 3000000000B
BLAST options error: File IGV.fa is empty
Traceback (most recent call last):
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 81, in mkref
    runner()
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 36, in __call__
    self.build_index()
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 76, in build_index
    subprocess.check_call(f"makeblastdb -parse_seqids -dbtype nucl -in {out_file_name}.fa", shell=True)
  File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'makeblastdb -parse_seqids -dbtype nucl -in IGV.fa' returned non-zero exit status 1.`

**To Troubleshot**
I think the isse NO.1 might cause by the wrong format but have no idea about another issue, so I did some troubleshots:
1. Format of one of the IMGT reference files showed as following:
`head -n 20 TRAJ.fasta`
![trouble1](https://github.com/singleron-RD/CeleScope/assets/149567592/5a1873ee-f353-4c48-a9f4-ae42bd1777a4)

`head -n 20 IGHD.fasta`
![trouble3](https://github.com/singleron-RD/CeleScope/assets/149567592/c805bc1f-cda7-495a-aaf2-a1c4d240ec74)

2.  Check whether the output directory is null:
`ls -al ../IG/human_IG`
![trouble2](https://github.com/singleron-RD/CeleScope/assets/149567592/6409c367-6d5a-4c4c-8c4c-095f4ac8e429)
but the "TR" directory is null. 
3. And I finally check version of celescope
**Version**
`celescope -v`
2.0.3

I sincerely expect some responses on resolution about these issues, or show me some normative format of IMGT data for constructing index file. Moreover, I hope that some detailed instance on how to construct index file about vdj or full length immune receptors sequencing.
Last question I would like to raise:
Whether the index files based on IMGT data between single cell vdj and full length immune receptor sequencing are coincident?

**Comment by Chenjunjie1996** [comment]
1. Make sure celescope version>=1.15.1 and refer to https://github.com/singleron-RD/CeleScope/blob/master/doc/assay/multi_vdj.md.
2. IMGT and full length vdj reference are different.

**Comment by Gethell** [comment]
Thanks for your response! I tried as [tutorial](https://github.com/singleron-RD/CeleScope/blob/master/doc/assay/multi_vdj.md) you provided, but unfortunately I encunted another issue while running codes like:
`wget https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR{A,B}{V,J}.fasta`
and 
`wget http://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Mus_musculus/IG/IG{H,K,L}{V,J}.fasta`
The issue descriped as:
> --2023-11-03 10:47:00--  https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR%7BA,B%7D%7BV,J%7D.fasta
正在解析主机 www.imgt.org (www.imgt.org)... 195.83.84.12
正在连接 www.imgt.org (www.imgt.org)|195.83.84.12|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2023-11-03 10:47:01 错误 404：Not Found。
<img width="1601" alt="trouble4" src="https://github.com/singleron-RD/CeleScope/assets/149567592/0d503f6e-ddab-4435-8cb8-04f2d2ff5926">

**Comment by Chenjunjie1996** [comment]
Remove character `\`
Correct link:
> wget https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR{A,B}{V,J}.fasta

**Comment by Gethell** [comment]
> Remove character `\` Correct link:
> 
> > wget [https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR{A,B}{V,J}.fasta](https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR%7BA,B%7D%7BV,J%7D.fasta)

Thanks for your response. And finally I succeed following your advise!

**Comment by Gethell** [comment]
> **Description** When I did as the tutorial on official [tweets](https://mp.weixin.qq.com/s/hqh7DJPzLsC45LepTI8Q7Q), I met some issues as running the following codes: `celescope vdj mkref human TR` but encounted issue like :
> 
> > Traceback (most recent call last):
> > File "/bios-store1/home/logcoin/.conda/envs/Celescope/bin/celescope", line 8, in 
> > sys.exit(main())
> > File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
> > args.func(args)
> > File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 81, in mkref
> > runner()
> > File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 35, in **call**
> > self.combine_seq()
> > File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper
> > result = func(*args, **kwargs)
> > File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 59, in combine_seq
> > assert len(imgt_files) == 7
> > AssertionError
> 
> And I run the code: `celescope vdj mkref human IG` I met another issue like:
> 
> > `Building a new DB, current time: 11/01/2023 15:27:28 New DB name:   /bios-store1/home/logcoin/Reference/hs_vdj/Homo_sapiens/IG/human_cele_BR/IGV.fa New DB title:  IGV.fa Sequence type: Nucleotide Deleted existing Nucleotide BLAST database named /bios-store1/home/logcoin/Reference/hs_vdj/Homo_sapiens/IG/human_cele_BR/IGV.fa Keep MBits: T Maximum file size: 3000000000B BLAST options error: File IGV.fa is empty Traceback (most recent call last):   File "/bios-store1/home/logcoin/.conda/envs/Celescope/bin/celescope", line 8, in <module>     sys.exit(main())   File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main     args.func(args)   File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 81, in mkref     runner()   File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 36, in __call__     self.build_index()   File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper     result = func(*args, **kwargs)   File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/site-packages/celescope/vdj/mkref.py", line 76, in build_index     subprocess.check_call(f"makeblastdb -parse_seqids -dbtype nucl -in {out_file_name}.fa", shell=True)   File "/bios-store1/home/logcoin/.conda/envs/Celescope/lib/python3.9/subprocess.py", line 373, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command 'makeblastdb -parse_seqids -dbtype nucl -in IGV.fa' returned non-zero exit status 1.`
> 
> **To Troubleshot** I think the isse NO.1 might cause by the wrong format but have no idea about another issue, so I did some troubleshots:
> 
> 1. Format of one of the IMGT reference files showed as following:
>    `head -n 20 TRAJ.fasta`
>    ![trouble1](https://private-user-images.githubusercontent.com/149567592/279625279-5a1873ee-f353-4c48-a9f4-ae42bd1777a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDI2OTYsIm5iZiI6MTcwMTI0MjM5NiwicGF0aCI6Ii8xNDk1Njc1OTIvMjc5NjI1Mjc5LTVhMTg3M2VlLWYzNTMtNGM0OC1hOWY0LWFlNDJiZDE3NzdhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNzE5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzhhZjkxYTJkNzgxMjM5MWU3MWNmZDZkMTcxYWFjOTZkZmM5YjA0OGU0YjY4YmRkMDg2YTBkOGE2Y2YzYTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iVmvmOgi_GnwD1AYm_Pdd1L76FO-2BTQfgxK-FIlWSo)
> 
> `head -n 20 IGHD.fasta` ![trouble3](https://private-user-images.githubusercontent.com/149567592/279631202-c805bc1f-cda7-495a-aaf2-a1c4d240ec74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDI2OTYsIm5iZiI6MTcwMTI0MjM5NiwicGF0aCI6Ii8xNDk1Njc1OTIvMjc5NjMxMjAyLWM4MDViYzFmLWNkYTctNDk1YS1hYWYyLWExYzRkMjQwZWM3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNzE5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzY4MjEwMDQ5N2Y3MWFmMDg4MDc1MjcxNDQ4ZDBhMTA5OWU4NzY2NDMyOTFiNjgxNzE0YTA2MDM2Mzk1M2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b0VEZQ-78Wpw6NGVs16Jzq0MtYP7DwBMQfWIuKQbli4)
> 
> 2. Check whether the output directory is null:
>    `ls -al ../IG/human_IG`
>    ![trouble2](https://private-user-images.githubusercontent.com/149567592/279627715-6409c367-6d5a-4c4c-8c4c-095f4ac8e429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDI2OTYsIm5iZiI6MTcwMTI0MjM5NiwicGF0aCI6Ii8xNDk1Njc1OTIvMjc5NjI3NzE1LTY0MDljMzY3LTZkNWEtNGM0Yy04YzRjLTA5NWY0YWM4ZTQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNzE5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDdmYWM0MDU0YjkxMmNlMTA0MGJlM2E4NDE3NTRkYjUwYzc4N2JjNGYyNGE5YTViZjliZTAwZTFjY2Y4NTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8RmV4ELq5lUCT3YrsU1ryYhE8YhEZEURcT90o68ys3E)
>    but the "TR" directory is null.
> 3. And I finally check version of celescope
>    **Version**
>    `celescope -v`
>    2.0.3
> 
> I sincerely expect some responses on resolution about these issues, or show me some normative format of IMGT data for constructing index file. Moreover, I hope that some detailed instance on how to construct index file about vdj or full length immune receptors sequencing. Last question I would like to raise: Whether the index files based on IMGT data between single cell vdj and full length immune receptor sequencing are coincident?

I found out the key of issue that there remained some undesired files when I mannually downloaded data from [IMGT](https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR). For instance, redundant file named "TRGJ" in the directory `Path/TR/`  made constructing reference failure.
![solution1](https://github.com/singleron-RD/CeleScope/assets/149567592/4140769e-1a5a-477f-9b06-be566ab0e715)

**Comment by Chenjunjie1996** [comment]
Our vdj pipeline focuses on alpha/beta TCR. 
Using following command to download only alpha/beta TCR sequence from IMGT to avoid error when running celescope vdj mkref.

 > wget [https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR{A,B}{V,J}.fasta](https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST_reference_directory/Homo_sapiens/TR/TR%7BA,B%7D%7BV,J%7D.fasta)
