### ISSUE TITLE
Problem in mkref command

### ISSUE THREAD

**Issue by AndreaGhiroldi** [singleron-RD/CeleScope#272]
Hi,

I was following the tutorial to install Celescope, but I had an issue with the mkref command:

(celescope) root@PT-DR-GHIROLDI:/home/aghiroldi/hs_ensemble_99# celescope rna mkref \
>  --genome_name Homo_sapiens_ensembl_99_filtered \
>  --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa \
>  --gtf Homo_sapiens.GRCh38.99.filtered.gtf \
>  --mt_gene_list mt_gene_list.txt
2024-02-16 09:55:30,298 - celescope.rna.mkref.run - INFO - start...
2024-02-16 09:55:30,298 - celescope.rna.mkref.build_rna_star_index - INFO - start...
STAR \
--runMode genomeGenerate \
--runThreadN 6 \
--genomeDir ./ \
--genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--sjdbGTFfile Homo_sapiens.GRCh38.99.filtered.gtf \
--sjdbOverhang 100 \
--genomeSAindexNbases 14 \

   /root/miniconda3/envs/celescope/bin/STAR-avx2 --runMode genomeGenerate --runThreadN 6 --genomeDir ./ --genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile Homo_sapiens.GRCh38.99.filtered.gtf --sjdbOverhang 100 --genomeSAindexNbases 14
        STAR version: 2.7.11a   compiled: 2023-09-15T02:58:53+0000 :/opt/conda/conda-bld/star_1694746407721/work/source
Feb 16 09:55:30 ..... started STAR run
Feb 16 09:55:30 ... starting to generate Genome files
Feb 16 09:56:14 ..... processing annotations GTF
Feb 16 09:56:40 ... starting to sort Suffix Array. This may take a long time...
Feb 16 09:56:48 ... sorting Suffix Array chunks and saving them to disk...
/root/miniconda3/envs/celescope/bin/STAR: line 8: 1222609 Killed                  "${cmd}" "$@"
Traceback (most recent call last):
  File "/root/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/root/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/rna/mkref.py", line 50, in mkref
    runner.run()
  File "/root/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/root/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/rna/mkref.py", line 44, in run
    self.build_rna_star_index()
  File "/root/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/root/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/rna/mkref.py", line 40, in build_rna_star_index
    subprocess.check_call(cmd, shell=True)
  File "/root/miniconda3/envs/celescope/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'STAR \
--runMode genomeGenerate \
--runThreadN 6 \
--genomeDir ./ \
--genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--sjdbGTFfile Homo_sapiens.GRCh38.99.filtered.gtf \
--sjdbOverhang 100 \
--genomeSAindexNbases 14 \
' returned non-zero exit status 137.

**Comment by zhouyiqi91** [comment]
An exit code of 137 usually means that the job was killed because it was using too much memory. It needs 32GB RAM to build the human genome index.

https://www.biostars.org/p/325468/

**Comment by AndreaGhiroldi** [comment]
Thank you. Solved with a VM
