### ISSUE TITLE
Auto Chemistry Detection Failing and FIFO File Generation Problem

### ISSUE THREAD

**Issue by Sandman-1** [singleron-RD/CeleScope#277]
Hello! Thank you for such an excellent software.

I am trying to run CeleScope v2.0.7 on raw fastqs from GSE203360, but it throws me the following error.

- Exception: Auto chemistry detection failed! `--chemistry auto` can auto-detect scopeV2 mRNA, scopeV3 mRNA, full length VDJ mRNA(flv_rna) and full length VDJ(flv). You need to explicitly use `--chemistry scopeV1` for legacy chemistry scopeV1. `--chemistry customized` is used for user defined combinations that you need to provide `--pattern`, `--whitelist` and `--linker` at the same time.

I don't know what the kit version is for GSE203360, but I tried supplying the latest version (scopeV3.0.1). It then gave me the following error.

- Exiting because of *FATAL ERROR*: could not create FIFO file .//Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53/01.starsolo/Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53__STARtmp/tmp.fifo.read1
SOLUTION: check the if run directory supports FIFO files.
If run partition does not support FIFO (e.g. Windows partitions FAT, NTFS), re-run on a Linux partition, or point --outTmpDir to a Linux partition.

Could you help me navigate these errors? I am working with WSL2 on my Windows computer.

**Comment by zhouyiqi91** [comment]
1. I have checked one run(SRR19312208) of GSE203360 and it is scopeV1. 
2. `Exiting because of FATAL ERROR: could not create FIFO file`
Please take a look at https://github.com/alexdobin/STAR/issues/1776
You can add extra STAR params by adding "--STAR_param --outTmpDir some_dir " to multi_rna

**Comment by Sandman-1** [comment]
Thank you! I am getting this error after adding the parameter, however. I add it to the end of the starsolo command within each sample-specific shell file.

- celescope rna starsolo: error: argument --STAR_param: expected one argument

**Comment by zhouyiqi91** [comment]
Sorry. It needs to be double quoted, like this `--STAR_param "--outTmpDir some_dir"`

**Comment by Sandman-1** [comment]
You are a lifesaver. Thank you so much! Curious, how do you know which GexScope kit version a run is?

**Comment by zhouyiqi91** [comment]
By checking the pattern of R1 reads. 
https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&page_size=10&acc=SRR19312208&display=reads
https://github.com/singleron-RD/CeleScope/blob/master/doc/chemistry.md

**Comment by Sandman-1** [comment]
Hello! I tried running the pipeline overnight, and it gave me this error when I woke up. 

- /usr/bin/STAR: line 7: 149706 Segmentation fault      "${cmd}" "$@"
Traceback (most recent call last):
  File "/home/hebbale/.local/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/hebbale/.local/lib/python3.10/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/home/hebbale/.local/lib/python3.10/site-packages/celescope/tools/starsolo.py", line 186, in starsolo
    q30_cb, q30_umi, chemistry = runner.run()
  File "/home/hebbale/.local/lib/python3.10/site-packages/celescope/tools/starsolo.py", line 177, in run
    self.run_starsolo()
  File "/home/hebbale/.local/lib/python3.10/site-packages/celescope/tools/starsolo.py", line 133, in run_starsolo
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'STAR \
--genomeDir /mnt/c/Users/hebbale/Downloads/human_GRCh38_optimized_v2_celescope \
--readFilesIn Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53/Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53_R2.fq.gz Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53/Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53_R1.fq.gz \
--readFilesCommand zcat \
--soloCBwhitelist None \
--soloCellFilter EmptyDrops_CR 3000 0.99 10 45000 90000 500 0.01 20000 0.001 10000 \
--outFileNamePrefix .//Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53/01.starsolo/Lung_GSE203360_IAC_mGGO_P1_Ground_Glass_Female_53_ \
--runThreadN 8 \
--clip3pAdapterSeq AAAAAAAAAAAA \
--outFilterMatchNmin 50 \
--soloFeatures Gene GeneFull_Ex50pAS \
--outSAMattributes NH HI nM AS CR UR CB UB GX GN  \
--soloType CB_UMI_Simple \
--soloCBstart 1 --soloCBlen 12  \
--soloUMIstart 13 --soloUMIlen 8  \
--soloCBmatchWLtype 1MM \
--outSAMtype BAM SortedByCoordinate \
--soloCellReadStats Standard \
--soloBarcodeReadLength 0 \
--outTmpDir /home/hebbale/tmp' returned non-zero exit status 139.

I don't understand what the segmentation fault refers to, or if it's a problem with the temporary directory I assigned file construction to in my linux partition, or if I am missing something else entirely. However, I think this should be the last error in the pipeline to run celescope properly. Could you please help me?

**Comment by zhouyiqi91** [comment]
Found an exit code 139 issue in STAR issue. https://github.com/alexdobin/STAR/issues/887 But it shouldn't be the same reason here.
I see that you are not using a conda environment; I'm not sure what version of STAR you are using. Could this be causing the problem?
