### ISSUE TITLE
Individual steps are not working.

### ISSUE THREAD

**Issue by araboapresyan** [singleron-RD/CeleScope#279]
**Describe the bug**
I tried to run multi_rna with individual steps but it works only for "sample" and "all" arguments.

**run.sh**
multi_rna\
        --mapfile ./my.mapfile\
        --genomeDir /media/arabo/DATA/genomes/xenopus_tropicalis/ncbi_UCB_Xtro_10.0/celescope_genome\
        --thread 8\
        --mod shell\
        --steps_run barcode

**Result**
$sh run.sh
2024-04-10 17:57:39,260 - celescope.tools.multi.parse_mapfile - INFO - start...
2024-04-10 17:57:39,267 - celescope.tools.multi.parse_mapfile - INFO - done. time used: 0:00:00.007206
Traceback (most recent call last):
  File "/home/arabo/anaconda3/envs/celescope/bin/multi_rna", line 8, in <module>
    sys.exit(main())
  File "/home/arabo/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/rna/multi_rna.py", line 40, in main
    multi.run()
  File "/home/arabo/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/multi.py", line 421, in run
    self.run_steps()
  File "/home/arabo/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/multi.py", line 382, in run_steps
    method_to_call(sample)
  File "/home/arabo/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/multi.py", line 284, in barcode
    cmd_line = self.get_cmd_line(step, sample)
  File "/home/arabo/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/multi.py", line 248, in get_cmd_line
    f'--outdir {self.outdir_dic[sample][step]} '
KeyError: 'barcode'

**Version**
2.0.7

**Comment by zhouyiqi91** [comment]
In celescope v2, there is no `barcode` step in `multi_rna`. Available steps are `sample`,`starsolo`,`analysis`.
https://github.com/singleron-RD/CeleScope/blob/master/celescope/rna/__init__.py

**Comment by araboapresyan** [comment]
Thanks.
 Then, is there any way to perform only barcoding step with V2, or to get intermediate fastq files?

**Comment by zhouyiqi91** [comment]
you can use the barcode step from other pipeline, for example,&nbsp;
celescope vdj barcode








 ----------Reply to Message----------
 On Thu, Apr 11, 2024 18:26 PM ***@***.***&gt; wrote:

  

 
Thanks.
 Then, is there any way to perform only barcoding step with V2, or to get intermediate fastq files?

**Comment by araboapresyan** [comment]
Thanks.Works for me.
