### ISSUE TITLE
1.12.0 can be installed, but failed to be run.

### ISSUE THREAD

**Issue by CaiCheng1996** [singleron-RD/CeleScope#281]
I have successfully installed version 2.0.7 and ran it with no problem, however, I failed to ran version 1.12.0 and got this error:

celescope rna --help
Traceback (most recent call last):
  File "/miniconda3/envs/celescope_old_1.12.0/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/celescope/celescope.py", line 31, in main
    step_module = utils.find_step_module(assay, step)
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/celescope/tools/utils.py", line 387, in find_step_module
    step_module = importlib.import_module(f"celescope.{assay}.{step}")
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/celescope/rna/analysis.py", line 2, in <module>
    from celescope.tools import analysis_wrapper
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/celescope/tools/analysis_wrapper.py", line 1, in <module>
    import scanpy as sc
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/miniconda3/envs/celescope_old_1.12.0/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

I have no idea why this happened.

**Comment by zhouyiqi91** [comment]
https://discourse.scverse.org/t/metaclass-conflict-from-trying-to-import-scanpy/1133
You can try to downgrade matplotlib <3.7 (e.g. 3.6.0)

**Comment by CaiCheng1996** [comment]
-

> https://discourse.scverse.org/t/metaclass-conflict-from-trying-to-import-scanpy/1133 You can try to downgrade matplotlib <3.7 (e.g. 3.6.0)

Yeah, that's helps. However, I got an another error: ImportError: cannot import name 'is_categorical' from 'pandas.api.types'. I then downgraded  pandas < 2.0 and it works now.

**Comment by zhouyiqi91** [comment]
> > https://discourse.scverse.org/t/metaclass-conflict-from-trying-to-import-scanpy/1133 You can try to downgrade matplotlib <3.7 (e.g. 3.6.0)
> 
> Yeah, that's helps. However, I got an another error: ImportError: cannot import name 'is_categorical' from 'pandas.api.types'. I then downgraded pandas < 2.0 and it works now.

good to know
