### ISSUE TITLE
FileNotFoundError: Did not find file SMA/outs/filtered/matrix.mtx.gz.

### ISSUE THREAD

**Issue by 2124sa** [singleron-RD/CeleScope#289]
Hello, I encountered this error while running CeleScope. 
Exiting because of *FATAL ERROR*: could not create FIFO file .//SMA/01.starsolo/SMA__STARtmp/tmp.fifo.read1
SOLUTION: check the if run directory supports FIFO files.
If run partition does not support FIFO (e.g. Windows partitions FAT, NTFS), re-run on a Linux partition, or point --outTmpDir to a Linux partition.

Jun 13 19:29:03 ...... FATAL ERROR, exiting
Traceback (most recent call last):
  File "/home/a2433/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/starsolo.py", line 186, in starsolo
    q30_cb, q30_umi, chemistry = runner.run()
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/starsolo.py", line 177, in run
    self.run_starsolo()
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/starsolo.py", line 133, in run_starsolo
    subprocess.check_call(cmd, shell=True)
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'STAR \
--genomeDir /mnt/e/sting/test_dir/Mm \
--readFilesIn /mnt/e/STING/scrnaseq/CleanData/SMA/SMA_2.fastq.gz /mnt/e/STING/scrnaseq/CleanData/SMA/SMA_1.fastq.gz \
--readFilesCommand zcat \
--soloCBwhitelist None \
--soloCellFilter EmptyDrops_CR 3000 0.99 10 45000 90000 500 0.01 20000 0.001 10000 \
--outFileNamePrefix .//SMA/01.starsolo/SMA_ \
--runThreadN 4 \
--clip3pAdapterSeq AAAAAAAAAAAA \
--outFilterMatchNmin 50 \
--soloFeatures Gene GeneFull_Ex50pAS \
--outSAMattributes NH HI nM AS CR UR CB UB GX GN  \
--soloType CB_UMI_Simple \
--soloCBstart 1 --soloCBlen 12  \
--soloUMIstart 13 --soloUMIlen 8  \
--soloCBmatchWLtype 1MM \
--outSAMtype BAM SortedByCoordinate \
--soloCellReadStats Standard \
--soloBarcodeReadLength 0 \
' returned non-zero exit status 112.
2024-06-13 19:29:04,273 - celescope.rna.analysis.analysis - INFO - start...
CeleScope version: 2.0.7 Args: Namespace(subparser_assay='rna', genomeDir='/mnt/e/sting/test_dir/Mm', matrix_file='.//SMA/outs/filtered', outdir='.//SMA/02.analysis', sample='SMA', thread='4', debug=False, func=<function analysis at 0x7fbee36d5550>)
CeleScope version: 2.0.7 Args: Namespace(subparser_assay='rna', genomeDir='/mnt/e/sting/test_dir/Mm', matrix_file='.//SMA/outs/filtered', outdir='.//SMA/02.analysis', sample='SMA', thread='4', debug=False, func=<function analysis at 0x7fbee36d5550>)
Traceback (most recent call last):
  File "/home/a2433/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/utils.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/rna/analysis.py", line 64, in analysis
    runner.run()
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/rna/analysis.py", line 38, in run
    with analysis_wrapper.Scanpy_wrapper(self.args, display_title=self.display_title) as scanpy_wrapper:
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/celescope/tools/analysis_wrapper.py", line 59, in __init__
    self.adata = sc.read_10x_mtx(
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/scanpy/readwrite.py", line 490, in read_10x_mtx
    adata = read(
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/scanpy/readwrite.py", line 554, in _read_v3_10x_mtx
    adata = read(
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/scanpy/readwrite.py", line 112, in read
    return _read(
  File "/home/a2433/miniconda3/envs/celescope/lib/python3.9/site-packages/scanpy/readwrite.py", line 737, in _read
    raise FileNotFoundError(f'Did not find file {filename}.')
FileNotFoundError: Did not find file SMA/outs/filtered/matrix.mtx.gz.

I employed two methodologies, both of which proved futile.
1.  nohup sh ./shell/*.sh &
2. sh /mnt/e/sting/scrnaseq/CleanData/shell/SMA.sh

I obtained shell access through this command.
multi_rna --mapfile ./my.mapfile.txt --genomeDir /mnt/e/sting/test_dir/Mm --thread 4 --mod shell --chemistry scopeV1

Here is my mapfile document.
SMA     /mnt/e/STING/scrnaseq/CleanData/SMA     SMA
SMC     /mnt/e/STING/scrnaseq/CleanData/SMC     SMC

I eagerly anticipate your assistance！

**Comment by zhouyiqi91** [comment]
```
Exiting because of FATAL ERROR: could not create FIFO file .//SMA/01.starsolo/SMA__STARtmp/tmp.fifo.read1
SOLUTION: check the if run directory supports FIFO files.
If run partition does not support FIFO (e.g. Windows partitions FAT, NTFS), re-run on a Linux partition, or point --outTmpDir to a Linux partition.
```

You can re-run on a Linux partition,
or point --outTmpDir to a Linux partition by adding `--STAR_param "--outTmpDir some_linux_dir" ` to `multi_rna`
