### ISSUE TITLE
auto chemistry detection failed!

### ISSUE THREAD

**Issue by seekyou123** [singleron-RD/CeleScope#29]
Dear developer,
I have managed to obtain the shell. But when I was running `sh ./shell/BBc1.sh`,it prompted an issue
```
....
 1, 'CGCATGGACACGCTTTTTTTTTTTTTTTTTTTA': 1, 'GATGCAAAAGTACTTTTTTTTTTTTTTTTTTTA': 1, 'GGTCTCAGGGGTGTTTTTTTTTTTTTTTTTTTA': 1, 'ATTTTGGCGTGAGTTTTTTTTTTTTTTTTTTTT': 1})
Traceback (most recent call last):
  File "/public/home/zhangjl/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/celescope.py", line 37, in main
    args.func(args)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/sample.py", line 29, in sample
    chemistry = ch.check_chemistry()
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/barcode.py", line 187, in check_chemistry
    chemistry = self.get_chemistry(fastq1)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/barcode.py", line 241, in get_chemistry
    raise Exception('auto chemistry detection failed!')
Exception: auto chemistry detection failed!
```
I think it is due to the parameter of `--chemistry auto`,but I dont know how to dealth with it...
The version of my celescope was
 ```
celescope --version
1.3.1
```

**Comment by zhouyiqi91** [comment]
Is this sample `BBc1` from Singleron?
If yes, ask the technical staff you are connecting with for the chemistry used. You need to use `--chemistry scopeV1` for `scopeV1`, and `--chemistry auto` is fine for `scopeV2.*` .

**Comment by seekyou123** [comment]
> Is this sample `BBc1` from Singleron?
> If yes, ask the technical staff you are connecting with for the chemistry used. You need to use `--chemistry scopeV1` for `scopeV1`, and `--chemistry auto` is fine for `scopeV2.*` .
Thank you very much!
Your advice helped me to solve the problem.
