### ISSUE TITLE
failing in featurecounts

### ISSUE THREAD

**Issue by seekyou123** [singleron-RD/CeleScope#31]
when i was running the module of `featurecounts`, I found the following issue:
```
Load annotation file 10x_genes.gtf ...                                     ||
Failed to open the annotation file /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref//public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref/10x_genes.gtf, or its format is incorrect, or it contains no 'exon' features.
Traceback (most recent call last):
  File "/public/home/zhangjl/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/celescope.py", line 37, in main
    args.func(args)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/featureCounts.py", line 142, in featureCounts
    featureCounts_obj.run()
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/featureCounts.py", line 107, in run
    self.run_featureCounts()
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/featureCounts.py", line 92, in run_featureCounts
    subprocess.check_call(cmd, shell=True)
  File "/public/home/zhangjl/miniconda3/envs/celescope/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'featureCounts -s 1 -a /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref//public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref/10x_genes.gtf -o .//BBc1/04.featureCounts/BBc1 -R BAM -T 8 -t exon .//BBc1/03.star/BBc1_Aligned.sortedByCoord.out.bam ' returned non-zero exit status 255.
```
by the way,I used the gtf downloaded from 10x rather than recommanded hs_ensembl_99,and I did not found any problems when I was running the `STAR `module.

**Comment by zhouyiqi91** [comment]
The problem is that `/public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref//public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref/10x_genes.gtf` is not a valid file path. You need to remove the duplicated path.

**Comment by seekyou123** [comment]
> The problem is that `/public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref//public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref/10x_genes.gtf` is not a valid file path. You need to remove the duplicated path.

Thank you for your guidance!
Nevertheless,I did not found any problems in the shell,
```
set -e
celescope rna sample --outdir .//BBc1/00.sample --sample BBc1 --assay rna --thread 8  --chemistry scopeV1 --fq1 /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/fastq/BBc1
/BBc1.raw_1.fq.gz 
celescope rna barcode --outdir .//BBc1/01.barcode --sample BBc1 --assay rna --thread 8 --chemistry scopeV1 --lowNum 2  --fq1 /public/home/zhangjl/CQ/scRNAseq/rawdata/ne
bc/fastq/BBc1/BBc1.raw_1.fq.gz --fq2 /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/fastq/BBc1/BBc1.raw_2.fq.gz 
celescope rna cutadapt --outdir .//BBc1/02.cutadapt --sample BBc1 --assay rna --thread 8 --minimum_length 20 --nextseq_trim 20 --overlap 10 --insert 150  --fq .//BBc1/0
1.barcode/BBc1_2.fq 
celescope rna star --outdir .//BBc1/03.star --sample BBc1 --assay rna --thread 8 --genomeDir /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref --outFilterMult
imapNmax 1 --starMem 30  --fq .//BBc1/02.cutadapt/BBc1_clean_2.fq 
celescope rna featureCounts --outdir .//BBc1/04.featureCounts --sample BBc1 --assay rna --thread 8 --gtf_type exon --genomeDir /public/home/zhangjl/CQ/scRNAseq/rawdata/
nebc/CeleScope/ref  --input .//BBc1/03.star/BBc1_Aligned.sortedByCoord.out.bam 
celescope rna count --outdir .//BBc1/05.count --sample BBc1 --assay rna --thread 8 --genomeDir /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref --expected_ce
ll_num 3000 --cell_calling_method auto  --bam .//BBc1/04.featureCounts/BBc1_name_sorted.bam --force_cell_num None 
celescope rna analysis --outdir .//BBc1/06.analysis --sample BBc1 --assay rna --thread 8 --genomeDir /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref  --matr
ix_file .//BBc1/05.count/BBc1_matrix_10X 
```

**Comment by zhouyiqi91** [comment]
You need to use relative file path when you run `celescope rna mkref`. 
A quick fix is to modify `celescope_genome.config` in the `genomeDir`: change `gtf = /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref/10x_genes.gtf` to `gtf=10x_genes.gtf`

**Comment by seekyou123** [comment]
> You need to use relative file path when you run `celescope rna mkref`.
> A quick fix is to modify `celescope_genome.config` in the `genomeDir`: change `gtf = /public/home/zhangjl/CQ/scRNAseq/rawdata/nebc/CeleScope/ref/10x_genes.gtf` to `gtf=10x_genes.gtf`

I got it!
Thank you very much!!
