### ISSUE TITLE
ModuleNotFoundError: No module named 'celescope.citeseq.Count_cite'

### ISSUE THREAD

**Issue by zh-zhang1984** [singleron-RD/CeleScope#50]
I follow the step in the document and when I run the code in Mac terminal:
```
celescope rna mkref \
 --genome_name Homo_sapiens_ensembl_99 \
 --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa \
 --gtf Homo_sapiens.GRCh38.99.gtf

```
 it reports error as follows, how can I solve this issue? 
```
(celescope) zhangzhongheng@x86_64-apple-darwin13 CeleScope % celescope rna mkref \
 --genome_name Homo_sapiens_ensembl_99 \
 --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa \
 --gtf Homo_sapiens.GRCh38.99.gtf
Traceback (most recent call last):
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/site-packages/celescope/tools/utils.py", line 658, in find_step_module
    step_module = importlib.import_module(f"celescope.{assay}.{step}")
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/site-packages/celescope/citeseq/count_cite.py", line 1, in <module>
    from .Count_cite import Count_cite
ModuleNotFoundError: No module named 'celescope.citeseq.Count_cite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/site-packages/celescope/tools/utils.py", line 661, in find_step_module
    step_module = importlib.import_module(f"celescope.tools.{step}")
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celescope.tools.count_cite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangzhongheng/opt/anaconda3/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/site-packages/celescope/celescope.py", line 30, in main
    step_module = utils.find_step_module(assay, step)
  File "/Users/zhangzhongheng/opt/anaconda3/lib/python3.8/site-packages/celescope/tools/utils.py", line 663, in find_step_module
    module_path = init_module.IMPORT_DICT[step]
KeyError: 'count_cite'

```

**Comment by zhouyiqi91** [comment]
1. Which version of celescope are you using? 
2. If you installed celescope correctly, the python version would be 3.6.7, not 3.8.

**Comment by zhouyiqi91** [comment]
Maybe you need to unset the `PYTHONPATH` when you install celescope, as in https://github.com/singleron-RD/CeleScope/issues/28#issuecomment-863841494

**Comment by zh-zhang1984** [comment]
`Successfully installed MarkupSafe-2.0.1 celescope-1.4.0 cutadapt-1.17 cython-0.29.24 descartes-1.1.0 editdistance-0.5.3 jinja2-3.0.1 joblib-1.0.1 matplotlib-3.3.0 mizani-0.7.3 palettable-3.3.0 patsy-0.5.1 plotly-4.14.3 plotnine-0.8.0 pysam-0.16.0.1 retrying-1.3.3 scikit-learn-0.24.2 scipy-1.5.0 sklearn-0.0 statsmodels-0.12.2 threadpoolctl-2.2.0 xopen-1.1.0`

The above output shows that the version is `celescope-1.4.0`

**Comment by zh-zhang1984** [comment]
And I also found the python version is correct:
```
(celescope) zhangzhongheng@x86_64-apple-darwin13 celescope % python --version 
Python 3.6.7
```
The python 3.8 version was in the base env
```
(base) zhangzhongheng@x86_64-apple-darwin13 celescope % python --version
Python 3.8.8
```
I also found that the error exist when I use other functions of celescope such as examine the version:

This works fine : 
```
(celescope) zhangzhongheng@x86_64-apple-darwin13 celescope % conda --version
conda 4.10.3
```
but this end up with the same error as before:

```
(celescope) zhangzhongheng@x86_64-apple-darwin13 celescope % celescope -h
Traceback (most recent call last):
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 658, in find_step_module
    step_module = importlib.import_module(f"celescope.{assay}.{step}")
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/site-packages/celescope/citeseq/count_cite.py", line 1, in <module>
    from .Count_cite import Count_cite
ModuleNotFoundError: No module named 'celescope.citeseq.Count_cite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 661, in find_step_module
    step_module = importlib.import_module(f"celescope.tools.{step}")
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celescope.tools.count_cite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/site-packages/celescope/celescope.py", line 30, in main
    step_module = utils.find_step_module(assay, step)
  File "/Users/zhangzhongheng/opt/anaconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 663, in find_step_module
    module_path = init_module.IMPORT_DICT[step]
KeyError: 'count_cite'
```

**Comment by zhouyiqi91** [comment]
I think the celescope installed in the base conda env may interfere with the one installed in the `celescope` env.
Will you please try:
1. uninstall celescope in the base conda env.
2. uninstall celescope in the `celescope` conda env.
3. reinstall celescope in the `celescope` conda env.

You can uninstall celescope with `pip uninstall celescope`

**Comment by zh-zhang1984** [comment]
I have tried to uninstall and reinstall the celescope, but the error seems still exist.

**Comment by zhouyiqi91** [comment]
When you do step2 and step3, you should activate the `celescope` conda env before running `pip uninstall celescope`.

**Comment by zhouyiqi91** [comment]
> I have tried to uninstall and reinstall the celescope, but the error seems still exist.

> When you do step2 and step3, you should activate the `celescope` conda env before running `pip uninstall celescope`.

Does this solve the problem?
